// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_bubblesort.cpp"
#include "EWIEGA46WW/moc_generaterandomnum.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_quicksort.cpp"
